image: alexwijn/docker-git-php-composer

pipelines:
  branches:
    staging:
      - step:
          script:
            - apt-get update
            - apt-get -qq install git-ftp
            - git ftp init --user $FTP_USERNAME --passwd $FTP_PASSWORD $FTP_ADDRESS/var/www/html/cmz-backend-test