image: alexwijn/docker-git-php-composer

pipelines:
  branches:
    staging:
      - step:
          script:
            - apt-get update
            - apt-get -qq install git-ftp
            - git ftp init -u $FTP_USERNAME -p $FTP_PASSWORD $FTP_ADDRESS/var/www/html/staging